# Generated by Django 5.0.6 on 2024-06-21 13:44

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Muscles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("Upper Body", "Upper Body"),
                            ("Lower Body", "Lower Body"),
                            ("Full Body", "Full Body"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.create_custom_path_for_image,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("Upper Body", "Upper Body"),
                            ("Lower Body", "Lower Body"),
                            ("Full Body", "Full Body"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "execution_description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("use_of_add_weight", models.BooleanField(default=False)),
                ("double_weight", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.create_custom_path_for_image,
                    ),
                ),
                (
                    "additional_muscles",
                    models.ManyToManyField(
                        blank=True, related_name="additional_muscles", to="app.muscles"
                    ),
                ),
                (
                    "core_muscles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_muscles",
                        to="app.muscles",
                    ),
                ),
            ],
        ),
    ]
